name: Update Typecho files

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Git configuration
        run: |
          git config --global user.name "gopcn"
          git config --global user.email "121377609+gopcn@users.noreply.github.com"

      - name: Get latest release
        id: get-latest-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: typecho/typecho
          excludes: prerelease, draft
          token: ${{ secrets.AUTH_PAT }}

      - name: Download and extract Typecho
        run: |
          curl -sL "https://github.com/typecho/typecho/releases/latest/download/typecho.zip" -o typecho.zip
          unzip -o typecho.zip && rm -f typecho.zip LICENSE.txt

      - name: Commit and push changes
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "${{ steps.get-latest-release.outputs.release }}"
          git push origin main